services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
  client:
    build:
      context: ./client
    expose:
      - "80"
    depends_on:
      - server
  server:
    build:
      context: ./server
    expose:
      - "3000"
    env_file:
      - ./server/.env
